include ../defs.mk

.PHONY: all
all: wayland.xml
	$(BINDIR)scanner $< $(INCDIR) $(SRCDIR)
#	$(BINDIR)scanner $< $(INCDIR)wayland-server-protocol.hpp $(INCDIR)wayland-client-protocol.hpp $(SRCDIR)wayland-protocol.cpp



